version: 0.7

data_dir: /quickwit/data

metastore_uri: http://quickwit:7280
otlp_http_listen_address: 0.0.0.0:7281
otlp_grpc_listen_address: 0.0.0.0:7282
rest_listen_address: 0.0.0.0:7280

storage:
  s3:
    endpoint: http://minio:9000
    bucket: quickwit
    region: auto
    access_key_id: quickwit
    secret_access_key: quickwit-secret
    force_path_style: true
    create_bucket_if_not_exists: true

indexing:
  create_index_if_not_exists: true

telemetry:
  enabled: false
