version: 0.8

cluster_id: ruxlog-cluster
node_id: ruxlog-quickwit-node
listen_address: 0.0.0.0
data_dir: /quickwit/qwdata

metastore_uri: file:///quickwit/data/indexes
default_index_root_uri: s3://quickwit/indexes

rest:
  listen_port: 7280

grpc:
  max_message_size: 20MiB

peer_seeds: []

indexer:
  enable_otlp_endpoint: true
  split_store_max_num_bytes: 100G
  split_store_max_num_splits: 1000

ingest_api:
  max_queue_memory_usage: 2GiB
  max_queue_disk_usage: 4GiB

searcher:
  aggregation_memory_limit: 500M
  aggregation_bucket_limit: 65000
  fast_field_cache_capacity: 1G
  split_footer_cache_capacity: 500M
  partial_request_cache_capacity: 64M
  max_num_concurrent_split_searches: 100
  max_num_concurrent_split_streams: 100
  split_cache:
    max_num_bytes: 1G
    max_num_splits: 10000
    num_concurrent_downloads: 1

jaeger:
  enable_endpoint: true

storage:
  s3:
    endpoint: http://minio:9000
    region: us-east-1
    access_key_id: quickwit
    secret_access_key: quickwit-secret
    force_path_style_access: true
    flavor: minio
