version: 0.8
cluster_id: ruxlog-quickwit-cluster
node_id: quickwit-node-1
listen_address: 0.0.0.0

rest:
  listen_port: 7280

grpc_listen_port: 7281

data_dir: /quickwit/data

metastore_uri: file:///quickwit/data/indexes

default_index_root_uri: file:///quickwit/data/indexes

indexer:
  split_store_max_num_bytes: 10G
  split_store_max_num_splits: 100
  max_concurrent_split_uploads: 2
  enable_otlp_endpoint: true

searcher:
  fast_field_cache_capacity: 256M
  split_footer_cache_capacity: 128M
  partial_request_cache_capacity: 32M
  max_num_concurrent_split_searches: 20
  max_num_concurrent_split_streams: 20

ingest_api:
  max_queue_memory_usage: 512M
  max_queue_disk_usage: 1G
