version: "0.1"
name: ${PROJECT}

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT}_backend
    restart: always
    ports:
      - "0.0.0.0:8888:8888"
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN:-backend.localhost}`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.middlewares=backend-rate@docker
      - traefik.http.middlewares.backend-rate.ratelimit.average=${BACKEND_RATE_AVG:-10}
      - traefik.http.middlewares.backend-rate.ratelimit.burst=${BACKEND_RATE_BURST:-20}
      - traefik.http.services.backend.loadbalancer.server.port=8888
      - traefik.docker.network=${PROJECT}_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network
    env_file:
      - .env.docker
    security_opt:
      - no-new-privileges:true

  postgres: # Will become myapp_postgres
    image: postgres:17.6-trixie
    container_name: ${PROJECT}_postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/postgres:/docker-entrypoint-initdb.d/
    ports:
      - "0.0.0.0:5000:5432"
    networks:
      - network
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-rroot} -d ${POSTGRES_DB:-ruxlog}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    user: postgres

  postgres_backup: # Will become myapp_backup
    container_name: ${PROJECT}_postgres_backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backups:/backups
    environment:
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    env_file:
      - .env.docker
    networks:
      - network

  redis:
    image: redis:7.4.5-alpine
    container_name: ${PROJECT}_redis
    restart: always
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD:-red}"
      --acl-pubsub-default allchannels
      --aclfile /etc/redis/users.acl
    volumes:
      - redis_data:/data
      - ./docker/redis/users.acl:/etc/redis/users.acl:ro # Changed path
    networks:
      - network
    ports:
      - "0.0.0.0:5001:6379"
    env_file:
      - .env.docker
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-u",
          "redis://${REDIS_USER:-rred}:${REDIS_PASSWORD:-red}@localhost:6379",
          "PING",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  redis_backup:
    image: offen/docker-volume-backup
    container_name: ${PROJECT}_redis_backup
    restart: always
    user: root # Required to access the volumes
    volumes:
      # Volume to backup
      - redis_data:/backup/redis:ro # Read-only access
      # Where to store the backups
      - ./backups/redis:/archive # Local backup storage
    environment:
      # Backup schedule
      - BACKUP_CRON_EXPRESSION=0 0 * * * # Daily at midnight
      # Backup retention
      - BACKUP_RETENTION_DAYS=7 # Keep backups for 7 days
      # Backup naming
      - BACKUP_PREFIX=${PROJECT}_redis # Prefix for backup files
      - BACKUP_SUFFIX=%Y-%m-%d-%H-%M # Date format suffix
      # - BACKUP_COMPRESSION=GZIP # Use GZIP compression
      # Notification on failure (optional)
      - NOTIFICATION_LEVEL=warning
      # Stop Redis before backup (optional but recommended)
      # - BACKUP_STOP_CONTAINER=${PROJECT}_redis
    networks:
      - network
    depends_on:
      - redis

volumes:
  postgres_data:
    name: ${PROJECT}_postgres_data
    driver: local
  redis_data:
    name: ${PROJECT}_redis_data
    driver: local

networks:
  network:
    name: ${PROJECT}_network
    driver: bridge
