version: "3.8"

services:
  # OpenObserve - Open source observability platform
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: ruxlog-openobserve
    ports:
      - "5080:5080"
    environment:
      # Root user credentials
      ZO_ROOT_USER_EMAIL: root@example.com
      ZO_ROOT_USER_PASSWORD: Complexpass#123
      # Data storage path
      ZO_DATA_DIR: /data
      # Enable OTLP ingestion
      ZO_OTLP_TRACES_ENABLED: "true"
      ZO_OTLP_METRICS_ENABLED: "true"
      ZO_OTLP_LOGS_ENABLED: "true"
    volumes:
      - openobserve_data:/data
    restart: unless-stopped
    networks:
      - ruxlog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  openobserve_data:
    driver: local

networks:
  ruxlog-network:
    driver: bridge
