mod about;
mod auth;
mod categories;
mod contact;
mod home;
mod advertise;
mod privacy_policy;
mod posts;
mod profile;
mod tags;
mod terms;

pub use about::*;
pub use auth::*;
pub use categories::*;
pub use contact::*;
pub use home::*;
pub use advertise::*;
pub use privacy_policy::*;
pub use posts::*;
pub use profile::*;
pub use tags::*;
pub use terms::*;
