version: "3.9"
name: ${PROJECT}

services:
  traefik:
    image: traefik:v3.1
    container_name: ${PROJECT}_traefik
    env_file:
      - .env.dev
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
    volumes:
      - ./traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - external_network
    restart: always

networks:
  external_network:
    name: ${PROJECT}_network
    external: true
