// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

#[derive(Queryable, Identifiable, Selectable, Debug, PartialEq)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password: String,
    pub avatar: Option<String>,
}
