version: 0.8

index_id: ruxlog-logs

index_uri: s3://quickwit/indexes/ruxlog-logs

doc_mapping:
  mode: dynamic
  timestamp_field: timestamp
  field_mappings:
    - name: timestamp
      type: datetime
      stored: true
      indexed: true
      fast: true
      fast_precision: milliseconds
      input_formats:
        - unix_timestamp
        - rfc3339
      output_format: rfc3339
    - name: message
      type: text
      stored: true
      indexed: true
      tokenizer: default
      record: position
    - name: level
      type: text
      stored: true
      indexed: true
      tokenizer: raw
      fast: true
    - name: service_name
      type: text
      stored: true
      indexed: true
      tokenizer: raw
      fast: true
    - name: span_id
      type: text
      stored: true
      indexed: true
      tokenizer: raw
    - name: trace_id
      type: text
      stored: true
      indexed: true
      tokenizer: raw
    - name: http_route
      type: text
      stored: true
      indexed: true
      tokenizer: default
    - name: scope
      type: text
      stored: true
      indexed: true
      tokenizer: default

search_settings:
  default_search_fields: [message, level, service_name, http_route, scope]

indexing_settings:
  commit_timeout_secs: 30
  merge_policy:
    type: stable_log
    min_level_num_docs: 100000
    merge_factor: 10
    max_merge_factor: 12
    maturation_period: 48h

retention:
  period: 14 days
  schedule: daily
