version: 0.8

index_id: ruxlog-traces

index_uri: s3://quickwit/indexes/ruxlog-traces

doc_mapping:
  mode: dynamic
  timestamp_field: timestamp
  field_mappings:
    - name: timestamp
      type: datetime
      stored: true
      indexed: true
      fast: true
      fast_precision: milliseconds
      input_formats:
        - unix_timestamp
        - rfc3339
      output_format: rfc3339
    - name: trace_id
      type: text
      stored: true
      indexed: true
      tokenizer: raw
      fast: true
    - name: span_id
      type: text
      stored: true
      indexed: true
      tokenizer: raw
      fast: true
    - name: parent_span_id
      type: text
      stored: true
      indexed: true
      tokenizer: raw
    - name: service_name
      type: text
      stored: true
      indexed: true
      tokenizer: raw
      fast: true
    - name: span_name
      type: text
      stored: true
      indexed: true
      tokenizer: default
      record: position
    - name: status_code
      type: text
      stored: true
      indexed: true
      tokenizer: raw
    - name: duration_ms
      type: f64
      stored: true
      indexed: true
      fast: true

search_settings:
  default_search_fields: [span_name, service_name, trace_id]

indexing_settings:
  commit_timeout_secs: 30
  merge_policy:
    type: stable_log
    min_level_num_docs: 100000
    merge_factor: 10
    max_merge_factor: 12
    maturation_period: 48h

retention:
  period: 7 days
  schedule: daily
