FROM nginx:1.24-alpine

# Remove default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your nginx configuration template
COPY ./nginx.conf.template.prod /etc/nginx/templates/default.conf.template

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
