#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REQUESTED_ENV="${1:-.env.dev}"
TARGET_FILE_REL="${2:-frontend/admin-dioxus/.env}"
if [[ "${REQUESTED_ENV}" = /* ]]; then
  ENV_PATH="${REQUESTED_ENV}"
else
  ENV_PATH="${PROJECT_ROOT}/${REQUESTED_ENV}"
fi
TARGET_PATH="${TARGET_FILE_REL}"
if [[ "${TARGET_FILE_REL}" != /* ]]; then
  TARGET_PATH="${PROJECT_ROOT}/${TARGET_FILE_REL}"
fi
if [[ ! -f "${ENV_PATH}" ]]; then
  echo "[sync-admin-env] Unable to find env file: ${ENV_PATH}" >&2
  exit 1
fi
set -a
# shellcheck disable=SC1090
source "${ENV_PATH}"
set +a
API_HOST="${ADMIN_APP_API_HOST:-}"
if [[ -z "${API_HOST}" ]]; then
  API_HOST="${SITE_URL:-http://localhost:8888}"
fi
API_HOST="${API_HOST#http://}"
API_HOST="${API_HOST#https://}"
API_HOST="${API_HOST%%/*}"
mkdir -p "$(dirname "${TARGET_PATH}")"
cat >"${TARGET_PATH}" <<ENV_FILE
# Autogenerated from ${ENV_PATH}
APP_API_URL=${API_HOST}
ENV_FILE
echo "[sync-admin-env] Wrote ${TARGET_PATH}" >&2
